const STORIES = 'https://github.com/zpthanos/production-stories/blob/main/stories/';
const story = (id, title, file, description, signals, keywords, priority) => ({
  id, title, type: 'SANITIZED PRODUCTION', description,
  url: `${STORIES}${file}`, signals, keywords, priority
});

window.evidence = [
  {
    id: 'production-stories', title: 'Production Engineering Stories', type: 'REAL PRODUCTION',
    description: '21 first-hand, sanitized cases covering customer delivery, incidents, integrations, QA, relationship recovery and support improvement.',
    url: 'https://github.com/zpthanos/production-stories',
    signals: ['customer ownership', 'production ownership', 'delivery judgment', 'communication', 'documentation'],
    keywords: ['client success', 'customer success', 'technical support', 'support engineer', 'technical account manager', 'tam', 'customer engineering', 'account management', 'production', 'escalation'], priority: 100
  },
  story('client-recovery', 'Recovering an unhappy client relationship', '17-client-relationship-recovery.md',
    'Reopened requirements, listened to dissatisfaction, coordinated changes and restored confidence through clear ownership and final approval.',
    ['customer ownership', 'communication', 'requirements', 'trust recovery', 'follow-through'],
    ['customer is unhappy', 'unhappy customer', 'frustrated client', 'relationship recovery', 'expectations', 'escalation', 'customer success'], 99),
  story('client-engagements', 'End-to-end client engagements', '07-end-to-end-client-engagements.md',
    'Customer discovery, requirements clarification, delivery decisions, expectation setting, incident communication and post-launch support.',
    ['customer ownership', 'requirements', 'delivery', 'incident communication', 'post-launch support'],
    ['end-to-end account ownership', 'technical account manager', 'tam', 'customer success', 'account management', 'stakeholder'], 98),
  story('ambiguous-request', 'Creating structure from an ambiguous request', '14-ambiguous-requirements.md',
    'Turned unclear business needs into concrete requirements, implementation decisions and reviewable outcomes.',
    ['requirements clarification', 'ambiguity reduction', 'technical translation', 'delivery decisions'],
    ['requirements are vague', 'vague requirements', 'unclear request', 'ambiguous', 'discovery', 'business need', 'tam'], 97),
  story('handover', 'WooCommerce operations and customer handover', '05-woocommerce-administration-handover.md',
    'Established workflows for a 2,000+ product store, configured the first 200 products and trained a non-technical owner for independent operation.',
    ['onboarding', 'customer enablement', 'training', 'WooCommerce', 'handover'],
    ['customer needs onboarding', 'adoption', 'enablement', 'customer success', 'catalogue'], 96),
  story('competing-priorities', 'Prioritization under competing demands', '15-competing-priorities.md',
    'Moved critical work first, preserved release checks and kept stakeholders informed while several client requests competed for attention.',
    ['prioritization', 'stakeholder communication', 'business impact', 'delivery control', 'release quality'],
    ['competing priorities', 'several customers need help', 'multiple customers', 'multitasking', 'deadlines', 'fast paced'], 95),
  story('business-value', 'Proactive business-value recommendation', '18-business-value-recommendation.md',
    'Identified an opportunity beyond the original brief and added digital menus with QR access so the website supported day-to-day guest service.',
    ['proactive recommendation', 'business value', 'customer experience', 'hospitality', 'growth mindset'],
    ['proactive business value', 'spot an opportunity', 'opportunity', 'growth', 'customer value', 'account growth'], 94),
  story('beyond-request', 'Delivering beyond the original request', '16-beyond-original-request.md',
    'Expanded a static business brief into a practical pricing, booking and partner-discovery experience after analysing how customers would use the service.',
    ['business analysis', 'consulting', 'customer journey', 'custom delivery', 'added value'],
    ['beyond original request', 'original request is not enough', 'customer journey', 'booking', 'proactive', 'customer success'], 93),
  story('checkout-conflict', 'Payment / checkout compatibility conflict', '03-payoneer-funnelkit-conflict.md',
    'Isolated a compatibility issue, identified the supported resolution and regression-tested the complete purchasing journey.',
    ['issue reproduction', 'payments', 'integration troubleshooting', 'regression testing', 'WooCommerce'],
    ['checkout', 'payment', 'cart', 'funnelkit', 'payoneer', 'integration', 'broken checkout', 'qa'], 92),
  story('malware-recovery', 'Critical malware recovery', '06-malware-recovery.md',
    'Safely recovered and relaunched a compromised ecommerce site with credential rotation, stakeholder communication and full customer-journey verification.',
    ['incident response', 'security', 'recovery', 'stakeholder communication', 'verification'],
    ['production incident', 'outage', 'malware', 'security incident', 'site down', 'emergency'], 91),
  story('cache-complaints', 'Reducing recurring cache complaints', '19-recurring-cache-complaints.md',
    'Turned repeated customer frustration into a clearer troubleshooting process and reusable support guidance.',
    ['repeat support problem', 'root-cause thinking', 'caching', 'process improvement', 'repeat-ticket reduction'],
    ['same problem keeps returning', 'repeat tickets', 'recurring issue', 'knowledge base', 'runbook', 'self service'], 90),
  story('support-knowledge', 'Repeatable support knowledge', '21-repeatable-support-knowledge.md',
    'Converted solved production problems into reusable guidance, checklists and customer training material to reduce repeated support work.',
    ['documentation', 'knowledge transfer', 'runbooks', 'repeatable support', 'self-service'],
    ['knowledge base', 'repeat tickets', 'support process', 'reusable reply', 'training'], 89),
  story('banking-integration', 'Banking and checkout integration', '09-banking-checkout-integration.md',
    'Coordinated an Alpha Bank integration from requirements discovery through developer handoff and checkout verification.',
    ['API requirements', 'stakeholder coordination', 'developer handoff', 'checkout verification', 'regression testing'],
    ['api is failing', 'integration', 'banking api', 'alpha bank', 'webhook', 'smtp', 'stakeholder'], 88),
  story('controlled-updates', 'Controlled WordPress updates', '04-controlled-wordpress-updates.md',
    'Introduced core, theme and plugin updates through backups, staging, compatibility checks, regression testing and rollback planning.',
    ['release assurance', 'risk management', 'staging', 'rollback', 'regression testing'],
    ['need release confidence', 'release needs to be safe', 'updates', 'compatibility', 'qa', 'production support'], 87),
  story('portfolio-admin', 'WordPress portfolio administration', '01-wordpress-portfolio-administration.md',
    'Supported 60 production websites with controlled access, tested backups, maintenance, platform health and ongoing customer changes.',
    ['60 production sites', 'maintenance', 'backups', 'access control', 'platform health'],
    ['wordpress administration', 'portfolio', '60 sites', 'permissions', 'site health', 'application support'], 86),
  story('site-editor', 'WordPress Site Editor expertise', '02-wordpress-site-editor.md',
    'Delivered consistent site-wide customer changes through maintainable templates, global styles, navigation and reusable patterns.',
    ['customer delivery', 'WordPress', 'Site Editor', 'maintainable implementation', 'design consistency'],
    ['wordpress site editor', 'block themes', 'templates', 'global styles', 'website changes'], 85),
  story('dns-services', 'DNS and third-party services', '08-dns-third-party-services.md',
    'Production troubleshooting across DNS and external services, with evidence-led isolation and controlled changes.',
    ['DNS', 'third-party services', 'production troubleshooting', 'controlled change'],
    ['dns', 'network', 'integration', 'third party', 'external service', 'infrastructure', 'incident'], 84),
  story('pagespeed', 'PageSpeed improvement', '11-pagespeed-improvement.md',
    'Improved a production store from below 20 to above 75 while protecting catalogue, cart and checkout behaviour.',
    ['performance diagnosis', 'controlled change', 'regression testing', 'WooCommerce'],
    ['slow', 'performance', 'pagespeed', 'lighthouse', 'speed', 'cache', 'woocommerce'], 83),
  story('post-launch-cache', 'Post-launch caching defect', '13-post-launch-caching-defect.md',
    'Resolved stale stylesheet delivery while preserving the site’s broader caching and performance benefits.',
    ['production support', 'root-cause isolation', 'Cloudflare', 'caching', 'controlled change'],
    ['post launch', 'caching defect', 'stale css', 'styles not updating', 'cache purge'], 82),
  story('technical-seo', 'Technical SEO implementation', '12-technical-seo.md',
    'Improved crawl and indexing signals across client sites with redirects, canonicals, sitemaps, robots directives, metadata and structured data.',
    ['technical SEO', 'search diagnostics', 'structured data', 'indexing', 'client sites'],
    ['seo', 'indexing', 'metadata', 'canonicals', 'sitemaps', 'robots', 'schema'], 81),
  story('accessibility-defect', 'Accessibility-related checkout defect', '10-accessibility-checkout-defect.md',
    'Defect reproduction and verification around an accessibility-sensitive customer journey.',
    ['defect reproduction', 'accessibility', 'checkout', 'verification', 'QA'],
    ['accessibility', 'wcag', 'axe', 'checkout', 'defect', 'bug', 'reproduce', 'release'], 80),
  story('ai-workflow', 'Responsible AI-assisted delivery', '20-ai-assisted-productivity.md',
    'Used AI for structure and first drafts while keeping source verification, manual testing, confidentiality and final approval under human control.',
    ['workflow design', 'human verification', 'QA planning', 'documentation', 'compliance controls'],
    ['ai', 'workflow', 'productivity', 'documentation', 'qa planning', 'human approval'], 72),
  {
    id: 'playwright', title: 'WooCommerce Playwright', type: 'EXECUTABLE',
    description: 'End-to-end guest checkout testing with Playwright, axe accessibility checks, CI, traces, screenshots and machine-readable reports.',
    url: 'https://github.com/zpthanos/WooCommerce-Playwright', signals: ['Playwright', 'end-to-end QA', 'accessibility', 'CI', 'regression verification'],
    keywords: ['qa', 'testing', 'release', 'regression', 'playwright', 'typescript', 'accessibility', 'ci', 'checkout'], priority: 79
  },
  {
    id: 'washland', title: 'The Washland Portal', type: 'EXECUTABLE',
    description: 'PHP 8.2 and MySQL application with validation, prepared statements, JSON endpoints and explicit HTTP behaviour.',
    url: 'https://github.com/zpthanos/The-Washland-Portal', signals: ['PHP', 'MySQL', 'JSON endpoints', 'HTTP behaviour', 'validation'],
    keywords: ['api', 'backend', 'http', 'json', 'endpoint', 'database', 'mysql', 'php', 'rest'], priority: 78
  },
  {
    id: 'cloudflare', title: 'Cloudflare Security Starter', type: 'EXECUTABLE',
    description: 'Worker request controls, WAF templates, rate limiting, monitoring and staged rollout guidance with rollback thinking.',
    url: 'https://github.com/zpthanos/Cloudflare-Security-Starter', signals: ['Cloudflare', 'WAF', 'rate limiting', 'monitoring', 'safe rollout'],
    keywords: ['security', 'waf', 'cloudflare', 'rate limit', 'monitoring', 'rollback', 'secure'], priority: 77
  },
  {
    id: 'browserstack', title: 'BrowserStack Business Testing', type: 'EXECUTABLE',
    description: 'Cross-browser automation, Playwright/TypeScript, secure configuration, GitHub Actions, test operations and release guidance.',
    url: 'https://github.com/zpthanos/Browserstack-Business-Testing', signals: ['cross-browser QA', 'Playwright', 'BrowserStack', 'CI', 'release guidance'],
    keywords: ['qa', 'cross browser', 'browserstack', 'test', 'release', 'regression', 'ci', 'typescript'], priority: 76
  },
  {
    id: 'civicflow', title: 'CivicFlow', type: 'PORTFOLIO CASE',
    description: 'Requirements-first delivery case study covering business rules, acceptance criteria, traceability, test strategy and release discipline.',
    url: 'https://github.com/zpthanos/civicflow-portfolio', signals: ['requirements engineering', 'acceptance criteria', 'traceability', 'test strategy', 'delivery discipline'],
    keywords: ['requirements', 'business analysis', 'acceptance criteria', 'traceability', 'uat', 'delivery', 'qa'], priority: 75
  },
  {
    id: 'secure-operations', title: 'Signals, secure communications & IT operations', type: 'SECURE OPERATIONS',
    description: 'Hellenic Army Signals / IT service as a Transmitter Cryptographer, including secure communications, mission-critical IT support and technical failure escalation/reporting involving NRDC-GR.',
    url: '#about', tab: 'defense', signals: ['secure communications', 'mission-critical IT', 'technical escalation', 'NRDC-GR', 'disclosure discipline'],
    keywords: ['nato', 'nrdc', 'military', 'army', 'signals', 'cryptographer', 'secure operations', 'escalation'], priority: 74
  }
];
