const intent = (label, prompt, aliases, summary, terms, strongest) => ({ label, prompt, aliases, summary, terms, strongest });

const intents = [
  intent('Customer recovery', 'Customer is unhappy', ['the customer is unhappy', 'unhappy customer', 'frustrated customer', 'relationship recovery', 'escalated customer'], 'Prioritizing ownership, expectation reset, requirements clarification, communication and confidence recovery.', ['customer ownership', 'communication', 'requirements', 'trust recovery'], ['client-recovery', 'client-engagements', 'ambiguous-request', 'handover', 'production-stories']),
  intent('Ambiguous requirements', 'Requirements are vague', ['the request is vague', 'vague requirements', 'unclear request', 'ambiguous request', 'discovery', 'business need'], 'Prioritizing clarification, business intent, implementation input, acceptance and reviewable outcomes.', ['requirements', 'ambiguity reduction', 'technical translation', 'delivery'], ['ambiguous-request', 'client-engagements', 'beyond-request', 'civicflow', 'client-recovery']),
  intent('Onboarding & handover', 'Onboarding and handover', ['customer needs onboarding', 'the customer needs onboarding', 'onboarding', 'handover', 'training', 'adoption', 'enablement'], 'Prioritizing practical enablement, workflow setup, training, documentation and customer independence.', ['onboarding', 'handover', 'training', 'customer enablement'], ['handover', 'client-engagements', 'support-knowledge', 'production-stories', 'site-editor']),
  intent('Competing priorities', 'Competing priorities', ['several customers need help', 'multiple customers', 'multitasking', 'too many requests', 'fast paced', 'prioritization'], 'Prioritizing business impact, urgency, dependencies, capacity and clear stakeholder expectations.', ['prioritization', 'stakeholder communication', 'business impact', 'delivery control'], ['competing-priorities', 'client-engagements', 'client-recovery', 'controlled-updates', 'production-stories']),
  intent('Proactive business value', 'Proactive business value', ['i spot an opportunity', 'spot an opportunity', 'opportunity', 'account growth', 'customer value', 'growth'], 'Prioritizing needs beyond the immediate request, practical recommendations and additional customer value.', ['proactive recommendation', 'business value', 'customer experience', 'added value'], ['business-value', 'beyond-request', 'client-engagements', 'handover', 'production-stories']),
  intent('Beyond the original request', 'Beyond original request', ['the original request is not enough', "the original request isn't enough", 'go beyond the brief', 'added value', 'consulting'], 'Prioritizing business analysis, customer-journey thinking and useful delivery beyond a narrow initial brief.', ['business analysis', 'customer journey', 'consulting', 'added value'], ['beyond-request', 'business-value', 'ambiguous-request', 'client-engagements', 'civicflow']),
  intent('End-to-end account ownership', 'End-to-end account ownership', ['i own the account end-to-end', 'own the account', 'account ownership', 'customer ownership', 'account delivery'], 'Prioritizing discovery, requirements, delivery, expectation setting, incident communication and post-launch follow-through.', ['customer ownership', 'requirements', 'delivery', 'incident communication', 'post-launch support'], ['client-engagements', 'client-recovery', 'competing-priorities', 'ambiguous-request', 'handover']),
  intent('Repeat support problem', 'Repeat support problem', ['the same problem keeps returning', 'same problem keeps returning', 'repeat tickets', 'recurring issue', 'runbook', 'knowledge base', 'self service'], 'Prioritizing root-cause notes, reusable troubleshooting guidance and changes that reduce repeated support work.', ['repeat support problem', 'process improvement', 'root-cause thinking', 'repeat-ticket reduction'], ['cache-complaints', 'support-knowledge', 'post-launch-cache', 'production-stories', 'handover']),
  intent('Production incident', 'Production incident', ['something broke in production', 'incident', 'outage', 'site down', 'malware', 'emergency', 'production support'], 'Prioritizing containment, evidence, safe recovery, stakeholder communication and verified return to service.', ['incident response', 'recovery', 'production', 'verification', 'security'], ['malware-recovery', 'post-launch-cache', 'dns-services', 'production-stories', 'controlled-updates']),
  intent('API & integrations', 'API is failing', ['an integration is failing', 'integration', 'integration failure', 'webhook', 'http 403', 'json', 'endpoint', 'authentication'], 'Prioritizing external requirements, integration troubleshooting, reproducible requests, stakeholder coordination and verification.', ['integration', 'api requirements', 'checkout verification', 'stakeholder coordination'], ['banking-integration', 'checkout-conflict', 'washland', 'dns-services', 'client-engagements']),
  intent('Checkout & payments', 'Checkout broke', ['checkout', 'payment', 'payments', 'cart broken', 'purchase flow', 'woocommerce'], 'Prioritizing customer-impacting ecommerce flows, compatibility isolation and full-journey regression verification.', ['checkout', 'payment', 'woocommerce', 'integration', 'regression testing'], ['checkout-conflict', 'banking-integration', 'playwright', 'accessibility-defect', 'pagespeed']),
  intent('QA & release confidence', 'Need release confidence', ['a release needs to be safe', 'release needs to be safe', 'qa', 'quality assurance', 'testing', 'regression', 'release', 'accessibility'], 'Prioritizing controlled changes, reproducible tests, regression coverage, browser evidence and release verification.', ['release assurance', 'regression testing', 'verification', 'rollback'], ['controlled-updates', 'playwright', 'browserstack', 'checkout-conflict', 'accessibility-defect']),
  intent('Security & recovery', 'Security and recovery', ['security', 'waf', 'malware recovery', 'secure', 'cloudflare'], 'Prioritizing incident handling, controlled security changes, monitoring, recovery and operational discipline.', ['security', 'recovery', 'monitoring', 'controlled change'], ['malware-recovery', 'cloudflare', 'secure-operations', 'dns-services', 'production-stories']),
  intent('Secure operations / NATO context', 'NATO secure operations', ['secure operations context', 'nato', 'nrdc', 'army', 'military', 'signals', 'cryptographer'], 'Prioritizing secure communications context, mission-critical IT, technical escalation and careful public disclosure boundaries.', ['secure communications', 'mission-critical IT', 'technical escalation', 'nrdc-gr'], ['secure-operations', 'malware-recovery', 'cloudflare', 'dns-services']),
  intent('Customer success', 'Customer success', ['client success', 'client success specialist', 'customer success manager', 'csm', 'customer experience', 'retention'], 'Prioritizing relationship ownership, onboarding, proactive value, clear progress communication and customer outcomes.', ['customer ownership', 'onboarding', 'customer enablement', 'business value', 'communication'], ['client-recovery', 'client-engagements', 'handover', 'business-value', 'beyond-request', 'competing-priorities']),
  intent('Technical account ownership', 'Technical account manager', ['tam', 'technical account', 'account manager', 'solutions engineer', 'customer engineer', 'customer engineering'], 'Prioritizing technical relationship ownership, requirements, stakeholder coordination, delivery and escalation.', ['customer ownership', 'requirements', 'stakeholder coordination', 'delivery', 'technical escalation'], ['client-engagements', 'ambiguous-request', 'banking-integration', 'competing-priorities', 'client-recovery']),
  intent('Technical support', 'Technical support', ['technical support engineer', 'support engineer', 'customer support engineer', 'application support engineer', 'developer support', 'product support engineer', 'customer support'], 'Prioritizing ownership, reproduction, investigation, escalation, customer communication, verification and reusable guidance.', ['production ownership', 'troubleshooting', 'issue reproduction', 'customer communication', 'verification', 'documentation'], ['production-stories', 'malware-recovery', 'checkout-conflict', 'cache-complaints', 'support-knowledge', 'portfolio-admin'])
];
